const saldoInicial = 0

const janeiro = new Mes('Janeiro')
janeiro.adicionarLancamento(new Lancamento("Salário", "receita", 3000 ))
janeiro.adicionarLancamento(new Lancamento("Aluguel", "despesa", 1000 ))
janeiro.adicionarLancamento(new Lancamento("Conta de Luz", "despesa", 200 ))
janeiro.adicionarLancamento(new Lancamento("Conta de Água", "despesa", 150 ))
janeiro.adicionarLancamento(new Lancamento("Internet", "despesa", 100 ))
janeiro.adicionarLancamento(new Lancamento("Transporte", "despesa", 340 ))
janeiro.adicionarLancamento(new Lancamento("Lazer", "despesa", 300 ))
janeiro.adicionarLancamento(new Lancamento("Alimentação", "despesa", 500 ))
janeiro.adicionarLancamento(new Lancamento("Condomínio", "despesa", 300 ))
janeiro.adicionarLancamento(new Lancamento("Farmácia", "despesa", 10))
janeiro.calcularSaldo()

const fevereiro = new Mes("Fevereiro")
fevereiro.adicionarLancamento(new Lancamento("Salário", "receita", 3000))
fevereiro.adicionarLancamento(new Lancamento("Aluguel", "despesa", 1200))
fevereiro.adicionarLancamento(new Lancamento("Conta de Luz", "despesa", 100))
fevereiro.adicionarLancamento(new Lancamento("Conta de Água", "despesa", 250))
fevereiro.adicionarLancamento(new Lancamento("Internet", "despesa", 100))
fevereiro.adicionarLancamento(new Lancamento("Transporte", "despesa", 300))
fevereiro.adicionarLancamento(new Lancamento("Lazer", "despesa", 300))
fevereiro.adicionarLancamento(new Lancamento("Alimentação", "despesa", 1000))
fevereiro.adicionarLancamento(new Lancamento("Condomínio", "despesa", 300))
fevereiro.calcularSaldo()

const marco = new Mes("Março")
marco.adicionarLancamento(new Lancamento("Salário", "receita", 4000))
marco.adicionarLancamento(new Lancamento("Aluguel", "despesa", 1200))
marco.adicionarLancamento(new Lancamento("Conta de Luz", "despesa", 100))
marco.adicionarLancamento(new Lancamento("Conta de Água", "despesa", 250))
marco.adicionarLancamento(new Lancamento("Internet", "despesa", 100))
marco.adicionarLancamento(new Lancamento("Transporte", "despesa", 300))
marco.adicionarLancamento(new Lancamento("Lazer", "despesa", 300))
marco.adicionarLancamento(new Lancamento("Alimentação", "despesa", 500))
marco.adicionarLancamento(new Lancamento("Condomínio", "despesa", 1250))
marco.adicionarLancamento(new Lancamento("Farmácia", "despesa", 400))
marco.calcularSaldo()

const abril = new Mes ("Abril")

const ano = new Ano()
ano.adicionarMes(janeiro)
ano.adicionarMes(fevereiro)
ano.adicionarMes(marco)
ano.adicionarMes(abril)
ano.calcularSaldo()

console.log(ano.meses)
